<!DOCTYPE html>
<html lang="es">
<?php $page = 'sobre_nosotros' ?>
<?php require_once('head.phtml') ?>

<body>
    <style>

    </style>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <?php require_once('navbar.phtml') ?>
    <!-- Navbar End -->

    <!-- Entradas  -->
    <div class="container mt-5 mb-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="col-lg">
            <div class="tab-content w-100">
                <div class="row g-4 mb-5">
                    <div class="col-md-4">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/blog/noticia_1.jpg" alt="noticia">
                        </div>
                    </div>
                    <div class="col-md-8 blog-text">
                        <h3>Fitur: Feria Internacional de Turismo</h3>
                        <h5>(24 - 28 ENE 2024)</h5>
                        <p class="mb-5 blog-p">
                        Fitur es el punto de encuentro global para los profesionales del turismo y la feria líder para los mercados receptivos y emisores de Iberoamérica. 
                        FITUR es la primera cita anual para los profesionales del turismo mundial y la feria líder para los mercados receptivos y emisores de Iberoamérica.<br>
                        <a href="https://www.ifema.es/fitur" >Enlace</a>
                        </p>
                    </div>
                </div>
                <div class="row g-4 mb-5">
                    <div class="col-md-4">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/blog/noticia_2.jpg" alt="noticia-2">
                        </div>
                    </div>
                    <div class="col-md-8 blog-text">
                        <h3>HIP 2024, Horeca Professional Expo – Madrid</h3>
                        <h5">19-21 FEBRERO 2024 MADRID – IFEMA</h5>
                        <p class="mb-5 blog-p">
                        Hospitality 4.0 Congres el mayor Internacional de tendencias y nuevos conceptos Horeca Innovación, tendencias, productos y soluciones específicas para cada uno de los segmentos de la industria hotelera.<br>
                        <a href="https://www.expohip.com/" >Enlace</a>    
                    </p>
                    </div>
                </div>
                <div class="row g-4 mb-5">
                    <div class="col-md-4">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/blog/noticia_3.jpg" alt="noticia-3">
                        </div>
                    </div>
                    <div class="col-md-8 blog-text">
                        <h3>Meliá reabre el Palau de Congressos de Catalunya y prevé "recuperar" el volumen de actividad en 2024</h3>
                        <p class="mb-5 blog-p">
                            En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar continuamente nuestros procesos de producción y distribución.<br>
                            <a href=" https://www.europapress.es/economia/noticia-melia-reabre-palau-congressos-catalunya-preve-recuperar-volumen-actividad-2024-20231002130208.html">Enlace</a>
                        </p>
                    </div>
                </div>
                <div class="row g-4 mb-5">
                    <div class="col-md-4">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/blog/noticia_4.jpg" alt="noticia-4">
                        </div>
                    </div>
                    <div class="col-md-8 blog-text">
                        <h3>Cumbre de Turismo Sostenible de Skift – Sustainable Tourism Summit </h3>
                        <p class="mb-5">
                        Skift Global Forum es la conferencia insignia de Skift para la industria de viajes, que reúne a las mentes más importantes, incluidos los directores ejecutivos y otros líderes empresariales, analistas de la industria, investigadores, profesionales de marketing, etc.
                        <br>
                        <a href="https://www.revfine.com/es/pagina/skift-global-forum/">Enlace</a>
                        </p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fotos zig-zag end -->

    <!-- Footer Start -->
    <?php require_once('footer.phtml'); ?>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>