<div class="wow fadeIn" data-wow-delay="0.1s">
   <div class="container-fluid bg-dark text-light footer pt-5 wow fadeIn d-flex justify-content-center align-items-center" data-wow-delay="0.1s">
        <div class="container py-3" style="justify-content:center !important;">
            <div class="row g-3">
                <div class="col justify-content-center align-items-center">
                    <a href="index.phtml" class="btn btn-link">Inicio</a>
                    <a href="servicios.phtml" class="btn btn-link">Servicio</a>
                    <a href="sobre_nosotros.phtml" class="btn btn-link">Sobre nosotros</a>
                    <a href="contact.phtml" class="btn btn-link">Contacto</a>
                    <a href="blog.phtml" class="btn btn-link">Blog</a>
                </div>
                <div class="col justify-content-center align-items-center">
                    <h3 class="text-light mb-4">Gabal Commerce LLC</h3>
                    <p class="text-light">Contacto</p>
                    <p class="mb-2">sales@gabalcommerce.com</p>
                </div>
                <div class="col justify-content-center align-items-center">
                    <h4 class="text-light mb-4">Últimas novedades</h4>
                    <a href="blog.phtml" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap;" class="btn btn-link">Fitur: Feria Internacional de Turismo (24 - 28 ENE 2024)</a>
                    <a href="blog.phtml" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap;" class="btn btn-link">HIP 2024, Horeca Professional Expo – Madrid 19-21 FEBRERO 2024 MADRID – IFEMA.</a>
                    <a href="blog.phtml" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap;" class="btn btn-link">Meliá reabre el Palau de Congressos de Catalunya y prevé "recuperar" el volumen de actividad en 2024</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid py-3" style="background-color: #707070 !important;">
        <div class="navbar-nav d-flex  text-white px-4 px-lg-5" style="padding-right: 0 !important">
            Copyright 2023 Gabal Commerce | All Rights Reserved.
        </div>
    </div>
</div>