<head>
    <meta charset="utf-8">
    <title>Gabal</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="amenities hotels spa services" name="keywords">
    <meta name="description" content="Compra online amenities para hoteles de todas las categorías. Ofrecemos una amplia gama de productos de higiene y cuidado personal, para que tus huéspedes disfruten de una estancia perfecta." />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@600;700&family=Ubuntu:wght@400;500&display=swap" rel="stylesheet"> 

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
 
    <link href="lib/animate/animate.min.css" rel="stylesheet" async>
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" async>

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/style.css" rel="stylesheet">
</head>
