<!DOCTYPE html>
<html lang="es">
<?php $page = 'inicio' ?>
<?php require_once('head.phtml') ?>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <?php require_once('navbar.phtml') ?>
    <!-- Navbar End -->

    <!-- Foto Start -->
    <div class="container-fluid p-0">
        <div class="row">
            <div class="col-12  mx-auto">
                <div class="card">
                    <img class="card-img-bottom" src="img/index/foto_start.jpg" alt="foto-portada">
                    <div class="card-body">
                        <h1 class="card-title text-centern text-white display-3">Detalles, experiencias, amenities</h1>
                        <p class="card-text  text-white text-center">El secreto mejor guardado en una estancia inolvidable</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Foto End -->

    <!-- Productos Start -->
    <div class="container py-4 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div>
                <h1 class="mb-3 display-5 text-center">Amenities únicos</h1>
                <h2 class="text-center mb-3">Detalles de hospitalidad y Amenities que dejan huella</h2>
                <p class="text-center">En Gabal Commerce sabemos que no hay tiempo que perder y si que disfrutar, por eso ofrecemos lo que realmente necesitan nuestros clientes para que la experiencia de sus huéspedes sea única.<br>
                La mejor calidad del mercado al precio más competitivo. Somos el proveedor de garantía, no prometemos, ofrecemos y garantizamos el único producto que con el que se enamorarán sus visitantes.<br>
                Ustedes piden, nosotros nos adaptamos.</p>
            </div>
            <div class="row mt-5">
                <div class="col-md-4 mt-5">
                    <div class="box">
                        <h3 class="mt-5">Caja 1</h3>
                        <div class="texto">Texto de la caja 1</div>
                        <img src="img/index/productos1_1.jpg" alt="producto" loading="lazy">
                    </div>
                    <p class="mb-5 text-center productos-2-p">
                        Ofrecemos colecciones personalizadas adaptándonos a cualquier detalle y garantizando distinción en el diseño. Cada vez más, los pequeños detalles son los que el cliente recordará en sus estancias. 
                    </p>
                </div>
                <div class="col-md-4 mt-5">
                    <div class="box">
                        <h3 class="mt-5">Caja 2</h3>
                        <div class="texto">Texto de la caja 2</div>
                        <img src="img/index/productos1_2.jpg" alt="producto-2" loading="lazy">
                    </div>
                    <p class="mb-5 text-center productos-2-p">
                        ¿Imagina brindar a sus huéspedes una selección  de marcas únicas que reflejen la esencia de su hotel? Con  GabalCommerce es posible ya que contamos con los proveedores más exclusivos para cumplir expectativas.
                    </p>
                </div>
                <div class="col-md-4 mt-5">
                    <div class="box">
                        <h3 class="mt-5">Caja 3</h3>
                        <div class="texto">Texto de la caja 2</div>
                        <img src="img/index/productos1_3.jpg" alt="producto-3" loading="lazy">
                    </div>
                    <p class="mb-5 text-center productos-2-p">
                        Nuestras recomendaciones y presupuestos les harán no quedarse atrás.  Les escuchamos y les asesoramos para  que pueda ser  un actor protagonista en  la industria hotelera.                        
                    </p>
                </div>
            </div>
        </div>
    </div> 
    <!-- Productos End -->

    <!-- Amenities Start -->
    <div class="container-xxl service py-4 mt-5 mb-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            </div>
            <div class="row g-4 wow fadeInUp" data-wow-delay="0.3s">
                <div class="col-lg-4">
                    <div class="nav w-100 nav-pills me-4">
                        <button name="amenities wc" class="nav-link w-100 d-flex align-items-center text-start mb-4 active" data-bs-toggle="pill" data-bs-target="#tab-pane-1" type="button">
                            <h4 class="m-0">Amenities de Baño</h4>
                        </button>
                        <button name="amenities pen" class="nav-link w-100 d-flex align-items-center text-start mb-4" data-bs-toggle="pill" data-bs-target="#tab-pane-2" type="button">
                            <h4 class="m-0">Boligrafos Personalizados</h4>
                        </button>
                        <button  name="amenities spa" class="nav-link w-100 d-flex align-items-center text-start mb-4" data-bs-toggle="pill" data-bs-target="#tab-pane-3" type="button">
                            <h4 class="m-0">Amenities de SPA</h4>
                        </button>
                        <button name="amenities custom" class="nav-link w-100 d-flex align-items-center text-start mb-4" data-bs-toggle="pill" data-bs-target="#tab-pane-4" type="button">
                            <h4 class="m-0">Fabricación exclusiva Kits</h4>
                        </button>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="tab-content w-100">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <div class="row g-4">
                                <h2 class="mb-0">Amenities de Baño</h2>
                                <p>
                                ¿Por qué conformarse con lo estándar cuando puede brindar a sus huéspedes los amenities de baño verdaderamente excepcionales y diferenciadores? No se trata solo de agradecer a sus clientes, sino de impulsar su reputación y marca. 
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-2">
                            <div class="row g-4">
                                <h2 class="mb-0">Boligrafos Personalizados</h2>
                                <p>
                                Boligrafos Personalizados – ¡Hablemos sobre cómo elevar su presencia con estilo! El catálogo de boligrafos personalizados les hará destacar y poner su firma en el recuerdo de cada visitante.
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-3">
                            <div class="row g-4">
                                <h2 class="mb-0">Amenities de SPA</h2>
                                <p>
                                Amenities de SPA –  Impresionar a sus clientes y ofrecer la calidad que no tienen otros hoteles en su SPA, está a su disposición. Unamos la exclusividad y el lujo en un mismo espacio con nuestros amenities de SPA.
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-4">
                            <div class="row g-4">
                                <h2 class="mb-0">Fabricación exclusiva Kits</h2>
                                <p>
                                Cuéntenos sus necesidades y preferencias para mejorar cualquier categoría de amenities que desee. No solo nos encargamos de diseñarlo y presentarle una variedad de opciones para diferentes categorías si no que mejoramos los que hayan probado. 
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Amenities End -->

    <!-- Noticias start -->
    <div class="container mb-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="row">
        <h1 class="display-5 text-center">Últimas novedades</h1>
            <div class="col-md-3 py-2">
                <div class="box-noticias">
                    <img class="img-noticias" src="img/index/noticias_1.jpg" alt="noticia" loading="lazy">
                    <h3 class="text-center mt-2" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap">Fitur: Feria Internacional de Turismo</h3>
                    <p>
                        Fitur es el punto de encuentro global para los profesionales del turismo y la feria líder para los mercados receptivos y emisores de Iberoamérica. 
                        FITUR es la primera cita anual para los profesionales del turismo mundial y la feria líder para los mercados receptivos y emisores de Iberoamérica.<br>
                        <a href="https://www.ifema.es/fitur" >Enlace</a>
                    </p>
                </div>
            </div>
            <div class="col-md-3 py-2">
                <div class="box-noticias">
                    <img class="img-noticias" src="img/index/noticias_2.jpg" alt="noticia-2" loading="lazy">
                    <h3 class="text-center mt-2" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap">HIP 2024, Horeca Professional Expo – Madrid<</h3>
                    <p>
                        Hospitality 4.0 Congres el mayor Internacional de tendencias y nuevos conceptos Horeca Innovación, tendencias, productos y soluciones específicas para cada uno de los segmentos de la industria hotelera.<br>
                        <a href="https://www.expohip.com/" >Enlace</a>    
                    </p>
                </div>
            </div>
            <div class="col-md-3 py-2">
                <div class="box-noticias">
                    <img class="img-noticias" src="img/index/noticias_3.jpg" alt="noticia-3" loading="lazy">
                    <h3 class="text-center mt-2" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap">Meliá reabre el Palau de Congressos de Catalunya y prevé "recuperar" el volumen de actividad en 2024</h3>
                    <p style="max-height:430px;overflow:hidden;">
                    Meliá Hotels International ha reabierto el Palau de Congressos de Catalunya y "espera recuperar" en 2024 el volumen de actividad previo a la pandemia y al...<br>
                            <a href=" https://www.europapress.es/economia/noticia-melia-reabre-palau-congressos-catalunya-preve-recuperar-volumen-actividad-2024-20231002130208.html"> Enlace</a>
                        </p>
                </div>
            </div>
            <div class="col-md-3 py-2">
                <div class="box-noticias">
                    <img class="img-noticias" src="img/index/noticias_4.jpg" alt="noticia-4" loading="lazy">
                    <h3 class="text-center mt-2" style="max-width:230px;overflow:hidden;text-overflow: ellipsis; white-space: nowrap">Cumbre de Turismo Sostenible de Skift – Sustainable Tourism Summit</h3>
                    <p>
                        Skift Global Forum es la conferencia insignia de Skift para la industria de viajes, que reúne a las mentes más importantes, incluidos los directores ejecutivos y otros líderes empresariales, analistas de la industria, investigadores, profesionales de marketing, etc.
                        <br>
                        <a href="https://www.revfine.com/es/pagina/skift-global-forum/">Enlace</a>
                        </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Noticias end -->

    <!-- Footer Start -->
    <?php require_once('footer.phtml'); ?>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="back to top" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <!-- Template Javascript -->
    <script src="js/main.js"></script>

</body>

</html>