<!DOCTYPE html>
<html lang="en">
<?php
$page = 'servicios';
$categoria = $_GET['categoria'] ?? '';
?>

<?php require_once('head.phtml') ?>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <?php require_once('navbar.phtml') ?>
    <!-- Navbar End -->

    <!-- Texto start -->
    <div class="container-xxl service mt-5">
        <div class="container">
            <div class="wow fadeInUp" data-wow-delay="0.1s">
                <h1 class="mb-4 text-center">COLECCIONES PERSONALIZADAS</h1>
                <h3 class="mb-5 text-center">AMÉN, AMENITIES!!</h3>
                <p class="mb-5 text-center">
                Después de casi 2 años de búsqueda e investigación para encontrar los mejores materiales, fabricas y diseños, por fin tenemos la mejor colección de amenities de hotel y productos de acogida que pueda encontrar actualmente en el mercado.                 </p>
            </div>
            <div class="wow fadeInUp" data-wow-delay="0.1s">
                <h1 class="mb-4 text-center">GABAL COMMERCE, LA ELECCIÓN OBVIA</h1>
                <p class="mb-5 text-center">
                ¡Sus huéspedes se merecen “LA BIENVENIDA” y nuestra colección es la clave para dejarlos boquiabiertos!
                ¿Porque conformarse con lo de siempre si pueden optar por productos únicos? Para eso queremos ser socios en la misión de elevar la marca de cada uno de los hoteles con los que trabajamos.
                Lo logramos ofreciendo una calidad excelente, un catálogo en constante expansión, flexibilidad en las necesidades de nuestros clientes, tiempos de entrega imbatibles, y el precio más competitivo del mercado.
                Nuestro catálogo es un tesoro de experiencias únicas, donde cada artículo es una historia por contar y un regalo para los sentidos de los visitantes. 
                No somos simples proveedores, somos artesanos de la hospitalidad. 
                </p>
            </div>
        </div>
    </div>
    <!-- Texto end -->

    <!--Productos start  -->
    <div class="container mb-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="row">
            <h1 class="display-5 text-center">Productos</h1>
            <h4 class="mb-5 text-center">Dejen que les demos un breve paseo por los amenities que les podemos ofrecer</h4>
            <div class="col-md-4 py-2">                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_1.jpg" alt="servicio-1">
                     <h3 class="text-center mt-2 text-uppercase">kits de baño</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2">                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_2.jpg" alt="servicio-2">
                     <h3 class="text-center mt-2 text-uppercase">kits de spa</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2">                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_3.jpg" alt="servicio-3">
                     <h3 class="text-center mt-2 text-uppercase">kits de higiene</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-4 py-2">
                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_4.jpg" alt="servicio-4">
                     <h3 class="text-center mt-2 text-uppercase">amenities tecnologicos</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2">                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_5.jpg" alt="servicio-5">
                     <h3 class="text-center mt-2 text-uppercase">Sets de Bienvenida</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2">                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_6.jpg" alt="servicio-6">
                     <h3 class="text-center mt-2 text-uppercase">amenities Habitación</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-4 py-2">  
                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_7.jpg" alt="servicio-7">
                     <h3 class="text-center mt-2 text-uppercase">boligrafos personalizados</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2"> 
                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_8.jpg" alt="servicio-8">
                    <h3 class="text-center mt-2 text-uppercase">complementos</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
            <div class="col-md-4 py-2">                
                <div class="box-noticias">
                    <img class="img-productos mt-2" src="img/servicio/producto_9.jpg" alt="servicio-9">
                     <h3 class="text-center mt-2 text-uppercase">Otros amenities</h3>
                    <div class="overflow-hidden" style="max-height: 250px;">
                        <p class="p-producto">
                            En Gabalcommerce, consideramos que la sostenibilidad y la responsabilidad ambiental son
                            pilares fundamentales de nuestro compromiso con la calidad y la excelencia en el servicio.
                            Valoramos profundamente la importancia de minimizar nuestro impacto en el medio ambiente y
                            contribuir al bienestar del planeta. Trabajamos en estrecha colaboración con proveedores que
                            comparten nuestra visión de la sostenibilidad, lo que nos permite ofrecer amenities que
                            respetan los recursos naturales y reducen la huella ecológica. Además, nos mantenemos al
                            tanto de las últimas prácticas sostenibles y tecnologías innovadoras para mejorar
                            continuamente nuestros procesos de producción y distribución.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Productos end  -->

    <!-- Footer Start -->
    <?php require_once('footer.phtml'); ?>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>