<!DOCTYPE html>
<html lang="es">
<?php $page = 'sobre_nosotros' ?>
<?php require_once('head.phtml') ?>

<body>
    <style>


    </style>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

    <!-- Navbar Start -->
    <?php require_once('navbar.phtml') ?>
    <!-- Navbar End -->

    <!-- Carousel Start -->
    <div class="container-fluid p-0">
        <div id="header-carousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="w-100" src="img/sobre_nosotros/carousel-bg-1.jpg" style="max-height: 730px; object-fit: cover;" alt="imagen-de-fondo">
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="img/sobre_nosotros/carousel-bg-2.jpg" style="max-height: 730px; object-fit: cover;" alt="imagen-de-fondo-2">
                </div>
                <div class="carousel-item">
                    <img class="w-100" src="img/sobre_nosotros/carousel-bg-3.jpg" style="max-height: 730px; object-fit: cover;" alt="imagen-de-fondo-3">
                </div>
            </div>
            <button name="previous picture" class="carousel-control-prev" type="button" data-bs-target="#header-carousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Anterior</span>
            </button>
            <button name="next picture" class="carousel-control-next" type="button" data-bs-target="#header-carousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Siguiente</span>
            </button>
        </div>
    </div>
    <!-- Carousel End -->

    <!-- Texto start -->
    <div class="container-xxl service mt-5">
        <div class="container">
            <div class="wow fadeInUp" data-wow-delay="0.1s">
                <h1 class="mb-4 text-center">SOBRE NOSOTROS</h1>
                <p class="mb-5 text-center">
                Nuestra historia empieza en 2022, cuando dos hermanos, unidos por una visión común, se embarcaron en un viaje para crear algo verdaderamente especial y significativo en el mundo de la hostelería. Ese fue el comienzo de una emocionante odisea destinada a brindar lo mejor a nuestros apreciados clientes, una pasión que hoy en día sigue siendo el latido constante que impulsa nuestro negocio. En Gabal Commerce, somos auténticos expertos en la importación y exportación de amenities  especialmente diseñados para el sector hotelero y la restauración.                 </p>
            </div>

        </div>
    </div>
    <!-- Texto end -->

    <!-- Fotos zig-zag start desktop -->
    <div class="container zig-zag-desktop mt-5 mb-5 degradado-crema wow fadeInUp" data-wow-delay="0.1s">
        <div class="col-lg">
            <div class="tab-content w-100">
                <div class="row g-4">
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-1.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                    <div class="col-md-6 mt-5">
                        <h3 class="text-center h3-sobre-nosotros">CALIDAD Y GARANTIA</h3>
                        <p class="mb-5 text-center">
                        En Gabalcommerce, la calidad es nuestro estandarte. Cada aspecto de nuestro servicio, desde la selección de proveedores hasta la importación y exportación, se somete a un riguroso escrutinio por parte de expertos en calidad. Esta dedicación se traduce en entregas puntuales y amenities excepcionales que superan expectativas. No solo nos conformamos con la excelencia, nos esforzamos por superarla mediante pruebas de calidad y retroalimentación constante para mantenernos a la vanguardia de la industria. En Gabalcommerce, la calidad es nuestra promesa y nuestra obsesión. 
                        </p>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-md-6 mt-5">
                        <h3 class="text-center h3-sobre-nosotros">DISEÑO Y MISIÓN</h3>
                        <p class="mb-5 text-center">
                            En Gabalcommerce, nuestra distinción radica en nuestra excepcional capacidad para ofrecer
                            servicios de personalización y diseño exclusivo de amenities. Nuestro proceso de
                            personalización comienza con una colaboración cercana con el cliente, donde entendemos sus
                            necesidades y aspiraciones con tal de trabajar en la creación de productos personalizados que
                            reflejen la identidad y los valores de cada colaborador.
                        </p>
                    </div>
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-2.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-3.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                    <div class="col-md-6 mt-5">
                        <h3 class="text-center h3-sobre-nosotros">VISIÓN Y FUTURO</h3>
                        <p class="mb-5">
                        En Gabalcommerce, nos esforzamos constantemente por desarrollar productos con materiales más sostenibles y ecológicos. Nuestro compromiso con la calidad y la responsabilidad ambiental se refleja en cada detalle y trabajamos incansablemente para minimizar nuestro impacto en el planeta. Únase a nosotros en el viaje hacia una hospitalidad más sostenible.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fotos zig-zag end -->

    <!-- Fotos zig-zag start mvl -->
    <div class="container zig-zag-mvl mt-5 mb-5 wow fadeInUp" data-wow-delay="0.1s" style="display:none">
        <div class="col-lg">
            <div class="tab-content w-100">
                <div class="row g-4">
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-1.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3 class="text-center">CALIDAD Y GARANTIA</h3>
                        <p class="mb-5 text-center">
                        En Gabalcommerce, la calidad es nuestro estandarte. Cada aspecto de nuestro servicio, desde la selección de proveedores hasta la importación y exportación, se somete a un riguroso escrutinio por parte de expertos en calidad. Esta dedicación se traduce en entregas puntuales y amenities excepcionales que superan expectativas. No solo nos conformamos con la excelencia, nos esforzamos por superarla mediante pruebas de calidad y retroalimentación constante para mantenernos a la vanguardia de la industria. En Gabalcommerce, la calidad es nuestra promesa y nuestra obsesión. 
                        </p>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-2.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3 class="text-center">DISEÑO Y MISIÓN</h3>
                        <p class="mb-5 text-center">
                            En Gabalcommerce, nuestra distinción radica en nuestra excepcional capacidad para ofrecer
                            servicios de personalización y diseño exclusivo de amenities. Nuestro proceso de
                            personalización comienza con una colaboración cercana con el cliente, donde entendemos sus
                            necesidades y aspiraciones con tal de trabajar en la creación de productos personalizados que
                            reflejen la identidad y los valores de cada colaborador.
                        </p>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-md-6" style="padding: 0 !important;">
                        <div class="position-relative h-50">
                            <img class="card-img-bottom" src="img/sobre_nosotros/zigzag-3.jpg" alt="paisaje-montaña">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3 class="text-center">VISIÓN Y FUTURO</h3>
                        <p class="mb-5 text-center">
                        En Gabalcommerce, nos esforzamos constantemente por desarrollar productos con materiales más sostenibles y ecológicos. Nuestro compromiso con la calidad y la responsabilidad ambiental se refleja en cada detalle y trabajamos incansablemente para minimizar nuestro impacto en el planeta. Únase a nosotros en el viaje hacia una hospitalidad más sostenible.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fotos zig-zag end -->
    
    <!-- Footer Start -->
    <?php require_once('footer.phtml'); ?>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/wow/wow.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>